title: Gokhan SALTIK
logo: assest/img/ProfilePicture.png
#description: text below image
#show_downloads: true
theme: jekyll-theme-minimal

baseurl: "/web"  # This should match the repository name if hosted at username.github.io/repository
url: "https://saltikg.github.io"

# Navigation Links
navbar:
  - name: "Home"
    link: "/"
  - name: "Professional Summary"
    link: "/professional-summary"
  - name: "Projects"
    link: "/projects"
  - name: "Contact"
    link: "/contact"
    
