
title: Gokhan SALTIK
logo: /assets/img/headshot_circle.png
description: Data Analytics & ML 
show_downloads: true
theme: jekyll-theme-minimal
#theme: cayman@v0.2.0
#remote_theme: pages-themes/cayman@v0.2.0
