title: Gokhan SALTIK
logo: assest/img/ProfilePicture.png

baseurl: "/web"  # Use /web since your site is served from this folder 
url: "https://saltikg.github.io"
theme: jekyll-theme-minimal  # Optional, specify if you are using a theme
